from .patient_illnessdata_view import PatientIllnessDataView
from .patient_doctor_views import PatientsDoctorListView, PatientDoctorDetailView, PatientDoctorAddView
from .doctor_auth_view import DoctorAuthView
from .doctor_registration_view import DoctorRegistrationView
