# Generated by Django 3.0.4 on 2020-03-21 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Doctor Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Doctor Surname')),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Doctor Email Address')),
                ('ssnid', models.CharField(max_length=30, unique=True, verbose_name='Doctor Health System Id')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illnessStatus', models.IntegerField(choices=[(0, 'healthy'), (1, 'ill_at_home'), (2, 'hospitalized')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessStatusHasPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUpdate', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('illness_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staysafemed.IllnessStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=45, unique=True)),
                ('mobile_number_1', models.CharField(blank=True, max_length=30)),
                ('mobile_number_2', models.CharField(blank=True, max_length=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staysafemed.Doctor')),
                ('illness_status', models.ManyToManyField(through='staysafemed.IllnessStatusHasPatient', to='staysafemed.IllnessStatus')),
            ],
        ),
        migrations.AddField(
            model_name='illnessstatushaspatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staysafemed.Patient'),
        ),
    ]
