# Generated by Django 3.0.4 on 2020-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staysafemed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnessdata',
            name='breath_frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='illnessdata',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='illnessdata',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='illnessdata',
            name='systolic_pressure',
            field=models.IntegerField(),
        ),
    ]
