# Generated by Django 3.0.4 on 2020-03-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staysafemed', '0002_auto_20200322_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='illness_status',
        ),
        migrations.AddField(
            model_name='patient',
            name='illness_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staysafemed.IllnessStatus'),
            preserve_default=False,
        ),
    ]
