# Generated by Django 3.0.4 on 2020-03-21 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import staysafemed.models.patient_otp


class Migration(migrations.Migration):

    dependencies = [
        ('staysafemed', '0002_auto_20200321_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, default=staysafemed.models.patient_otp.generateOtp, max_length=8, null=True)),
                ('date_issued', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_expire', models.DateTimeField(default=staysafemed.models.patient_otp.expireDate)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staysafemed.Patient')),
            ],
        ),
    ]
