# Generated by Django 3.0.4 on 2020-03-21 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staysafemed', '0003_patientotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breath_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hear_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('systolic_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('date_create', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_delete', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='illnessstatushaspatient',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='illness_data',
            field=models.ManyToManyField(to='staysafemed.IllnessData'),
        ),
    ]
