# Generated by Django 3.0.4 on 2020-03-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staysafemed', '0004_auto_20200322_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='illness_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staysafemed.IllnessStatus'),
        ),
    ]
